export const categories = [
  "Sports",
  "Arts",
  "Science",
  "Technology",
  "Music",
  "Literature",
  "Social",
];

export const types = [
  "Workshop",
  "Competition",
  "Seminar",
  "Training",
  "Exhibition",
  "Performance",
  "Club",
];

export const levels = ["Beginner", "Intermediate", "Advanced", "Expert"];

export const durations = [
  "1 Hour",
  "2 Hours",
  "Half Day",
  "Full Day",
  "Week Long",
];

export const statuses = ["active", "inactive", "pending"];

export const departments = [
  "Computer Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electronics",
  "Information Technology",
  "Business Administration",
  "Arts & Humanities",
];

export const classes = [
  "CSE-A",
  "CSE-B",
  "ECE-A",
  "ECE-B",
  "ME-A",
  "ME-B",
  "IT-A",
  "IT-B",
  "CE-A",
  "BA-A",
  "AH-A",
];

export const years = [1, 2, 3, 4];

export const semesters = [1, 2, 3, 4, 5, 6, 7, 8];

const mockStudents = [
  {
    id: "s1",
    name: "Alice Johnson",
    rollNumber: "CSE2021001",
    class: "CSE-A",
    department: "Computer Science",
    year: 3,
    semester: 5,
    email: "alice.j@univ.edu",
  },
  {
    id: "s2",
    name: "Bob Smith",
    rollNumber: "ECE2021015",
    class: "ECE-A",
    department: "Electrical Engineering",
    year: 3,
    semester: 5,
    email: "bob.s@univ.edu",
  },
  {
    id: "s3",
    name: "Carol White",
    rollNumber: "ME2022008",
    class: "ME-A",
    department: "Mechanical Engineering",
    year: 2,
    semester: 4,
    email: "carol.w@univ.edu",
  },
  {
    id: "s4",
    name: "David Brown",
    rollNumber: "IT2021022",
    class: "IT-A",
    department: "Information Technology",
    year: 3,
    semester: 6,
    email: "david.b@univ.edu",
  },
  {
    id: "s5",
    name: "Emma Davis",
    rollNumber: "CSE2022011",
    class: "CSE-B",
    department: "Computer Science",
    year: 2,
    semester: 3,
    email: "emma.d@univ.edu",
  },
  {
    id: "s6",
    name: "Frank Miller",
    rollNumber: "ECE2020019",
    class: "ECE-B",
    department: "Electronics",
    year: 4,
    semester: 7,
    email: "frank.m@univ.edu",
  },
  {
    id: "s7",
    name: "Grace Wilson",
    rollNumber: "CE2023005",
    class: "CE-A",
    department: "Civil Engineering",
    year: 1,
    semester: 2,
    email: "grace.w@univ.edu",
  },
  {
    id: "s8",
    name: "Henry Taylor",
    rollNumber: "BA2022030",
    class: "BA-A",
    department: "Business Administration",
    year: 2,
    semester: 4,
    email: "henry.t@univ.edu",
  },
  {
    id: "s9",
    name: "Ivy Anderson",
    rollNumber: "CSE2023018",
    class: "CSE-A",
    department: "Computer Science",
    year: 1,
    semester: 1,
    email: "ivy.a@univ.edu",
  },
  {
    id: "s10",
    name: "Jack Thomas",
    rollNumber: "ME2021012",
    class: "ME-B",
    department: "Mechanical Engineering",
    year: 3,
    semester: 5,
    email: "jack.t@univ.edu",
  },
  {
    id: "s11",
    name: "Kate Martinez",
    rollNumber: "IT2020025",
    class: "IT-B",
    department: "Information Technology",
    year: 4,
    semester: 8,
    email: "kate.m@univ.edu",
  },
  {
    id: "s12",
    name: "Liam Garcia",
    rollNumber: "AH2022007",
    class: "AH-A",
    department: "Arts & Humanities",
    year: 2,
    semester: 3,
    email: "liam.g@univ.edu",
  },
];

export const mockActivities = [
  {
    id: "1",
    name: "Basketball Training",
    category: "Sports",
    type: "Training",
    level: "Intermediate",
    duration: "2 Hours",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-01-15",
    student: mockStudents[0],
  },
  {
    id: "2",
    name: "Painting Workshop",
    category: "Arts",
    type: "Workshop",
    level: "Beginner",
    duration: "Half Day",
    status: "active",
    assignedFacultyId: "f1",
    createdAt: "2024-01-16",
    student: mockStudents[1],
  },
  {
    id: "3",
    name: "Robotics Club",
    category: "Technology",
    type: "Club",
    level: "Advanced",
    duration: "2 Hours",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-01-17",
    student: mockStudents[2],
  },
  {
    id: "4",
    name: "Chess Competition",
    category: "Sports",
    type: "Competition",
    level: "Expert",
    duration: "Full Day",
    status: "pending",
    assignedFacultyId: null,
    createdAt: "2024-01-18",
    student: mockStudents[3],
  },
  {
    id: "5",
    name: "Piano Recital",
    category: "Music",
    type: "Performance",
    level: "Advanced",
    duration: "2 Hours",
    status: "active",
    assignedFacultyId: "f2",
    createdAt: "2024-01-19",
    student: mockStudents[4],
  },
  {
    id: "6",
    name: "Science Fair",
    category: "Science",
    type: "Exhibition",
    level: "Intermediate",
    duration: "Full Day",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-01-20",
    student: mockStudents[5],
  },
  {
    id: "7",
    name: "Creative Writing",
    category: "Literature",
    type: "Workshop",
    level: "Beginner",
    duration: "Half Day",
    status: "inactive",
    assignedFacultyId: "f3",
    createdAt: "2024-01-21",
    student: mockStudents[6],
  },
  {
    id: "8",
    name: "Football League",
    category: "Sports",
    type: "Competition",
    level: "Intermediate",
    duration: "Week Long",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-01-22",
    student: mockStudents[7],
  },
  {
    id: "9",
    name: "Photography Club",
    category: "Arts",
    type: "Club",
    level: "Beginner",
    duration: "1 Hour",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-01-23",
    student: mockStudents[8],
  },
  {
    id: "10",
    name: "AI Workshop",
    category: "Technology",
    type: "Workshop",
    level: "Expert",
    duration: "Full Day",
    status: "pending",
    assignedFacultyId: "f1",
    createdAt: "2024-01-24",
    student: mockStudents[9],
  },
  {
    id: "11",
    name: "Debate Club",
    category: "Social",
    type: "Club",
    level: "Intermediate",
    duration: "2 Hours",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-01-25",
    student: mockStudents[10],
  },
  {
    id: "12",
    name: "Guitar Lessons",
    category: "Music",
    type: "Training",
    level: "Beginner",
    duration: "1 Hour",
    status: "active",
    assignedFacultyId: "f2",
    createdAt: "2024-01-26",
    student: mockStudents[11],
  },
  {
    id: "13",
    name: "Chemistry Lab",
    category: "Science",
    type: "Training",
    level: "Advanced",
    duration: "Half Day",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-01-27",
    student: mockStudents[0],
  },
  {
    id: "14",
    name: "Poetry Reading",
    category: "Literature",
    type: "Performance",
    level: "Intermediate",
    duration: "2 Hours",
    status: "inactive",
    assignedFacultyId: null,
    createdAt: "2024-01-28",
    student: mockStudents[1],
  },
  {
    id: "15",
    name: "Web Development",
    category: "Technology",
    type: "Seminar",
    level: "Intermediate",
    duration: "Full Day",
    status: "active",
    assignedFacultyId: "f4",
    createdAt: "2024-01-29",
    student: mockStudents[2],
  },
  {
    id: "16",
    name: "Volleyball Camp",
    category: "Sports",
    type: "Training",
    level: "Beginner",
    duration: "Week Long",
    status: "pending",
    assignedFacultyId: null,
    createdAt: "2024-01-30",
    student: mockStudents[3],
  },
  {
    id: "17",
    name: "Sculpture Class",
    category: "Arts",
    type: "Workshop",
    level: "Advanced",
    duration: "Half Day",
    status: "active",
    assignedFacultyId: "f3",
    createdAt: "2024-01-31",
    student: mockStudents[4],
  },
  {
    id: "18",
    name: "Choir Practice",
    category: "Music",
    type: "Club",
    level: "Intermediate",
    duration: "2 Hours",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-02-01",
    student: mockStudents[5],
  },
  {
    id: "19",
    name: "Machine Learning Bootcamp",
    category: "Technology",
    type: "Training",
    level: "Expert",
    duration: "Week Long",
    status: "active",
    assignedFacultyId: null,
    createdAt: "2024-02-02",
    student: mockStudents[6],
  },
  {
    id: "20",
    name: "Swimming Competition",
    category: "Sports",
    type: "Competition",
    level: "Advanced",
    duration: "Full Day",
    status: "active",
    assignedFacultyId: "f5",
    createdAt: "2024-02-03",
    student: mockStudents[7],
  },
];

export const mockFaculty = [
  {
    id: "f1",
    name: "Dr. Sarah Johnson",
    department: "Computer Science",
    email: "sarah.johnson@university.edu",
  },
  {
    id: "f2",
    name: "Prof. Michael Chen",
    department: "Music",
    email: "michael.chen@university.edu",
  },
  {
    id: "f3",
    name: "Dr. Emily Williams",
    department: "Arts",
    email: "emily.williams@university.edu",
  },
  {
    id: "f4",
    name: "Prof. James Brown",
    department: "Technology",
    email: "james.brown@university.edu",
  },
  {
    id: "f5",
    name: "Dr. Lisa Anderson",
    department: "Sports",
    email: "lisa.anderson@university.edu",
  },
  {
    id: "f6",
    name: "Prof. David Miller",
    department: "Science",
    email: "david.miller@university.edu",
  },
  {
    id: "f7",
    name: "Dr. Jennifer Davis",
    department: "Literature",
    email: "jennifer.davis@university.edu",
  },
  {
    id: "f8",
    name: "Prof. Robert Wilson",
    department: "Social Sciences",
    email: "robert.wilson@university.edu",
  },
];
